In [49]:
import numpy as np
from itertools import combinations

In [50]:
r = np.random.randn(10,3) # distance array
print(r)
id = np.arange(10)

[[-0.77689665  0.28812707  0.71292736]
 [ 1.18561835  1.32297501  0.64408524]
 [ 0.82038305  0.6522369  -1.46439701]
 [ 0.59450328 -0.7199832  -1.40312991]
 [ 1.55626583 -0.46323351 -1.41391395]
 [ 0.42801373 -0.49757841  0.54394097]
 [ 0.0978091   0.17325611  1.00430751]
 [-1.70694483  0.29198756 -0.72474273]
 [-0.04779983  0.40209019 -0.05433662]
 [ 0.69606371 -0.07037857 -1.0672636 ]]


In [51]:
id_pair = np.asanyarray(list(combinations(id,2)))
print(id_pair)

[[0 1]
 [0 2]
 [0 3]
 [0 4]
 [0 5]
 [0 6]
 [0 7]
 [0 8]
 [0 9]
 [1 2]
 [1 3]
 [1 4]
 [1 5]
 [1 6]
 [1 7]
 [1 8]
 [1 9]
 [2 3]
 [2 4]
 [2 5]
 [2 6]
 [2 7]
 [2 8]
 [2 9]
 [3 4]
 [3 5]
 [3 6]
 [3 7]
 [3 8]
 [3 9]
 [4 5]
 [4 6]
 [4 7]
 [4 8]
 [4 9]
 [5 6]
 [5 7]
 [5 8]
 [5 9]
 [6 7]
 [6 8]
 [6 9]
 [7 8]
 [7 9]
 [8 9]]


In [60]:
x_pair = np.asanyarray(list(combinations(r[:,0],2)))
y_pair = np.asanyarray(list(combinations(r[:,1],2)))
z_pair = np.asanyarray(list(combinations(r[:,2],2)))

dx_pair = np.diff(x_pair, axis=1).ravel()
dy_pair = np.diff(y_pair, axis=1).ravel()
dz_pair = np.diff(z_pair, axis=1).ravel()

dx_pair = np.sqrt(dx_pair**2 + dy_pair**2 + dz_pair**2)

a = 3.14*dx_pair
x = id_pair[:,0]
print(x.size)


45
